name: Build and Push API Gateway Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -f api-gateway/pom.xml clean package

      - name: Build Docker image
        working-directory: ./api-gateway
        run: |
          docker build \
            --build-arg whatsapp_verify_token=${{ secrets.WHATSAPP_VERIFY_TOKEN }} \
            --build-arg whatsapp_graph_api_token=${{ secrets.WHATSAPP_GRAPH_API_TOKEN }} \
            --build-arg whatsapp_app_secret=${{ secrets.WHATSAPP_APP_SECRET }} \
            -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-gateway:latest .

      - name: Salvar artefatos
        uses: actions/upload-artifact@v3
        with:
            name: docker-image
            path: ./api-gateway

  push:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Download do artefato
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: ./api-gateway
      
      - name: Configurar gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Carregar a imagem Docker do artefato
        run: docker load -i api-gateway/api-gateway.tar

      - name: Taggear a imagem com SHA
        run: docker tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-gateway:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-gateway:${{ github.sha }}
      
      - name: Publicar a imagem no Artifact Registry
        run: |
          gcloud auth configure-docker gcr.io --quiet
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-gateway:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-gateway:${{ github.sha }}