name: Build and Push API Gateway Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -f api-gateway/pom.xml clean package

      - name: Build Docker image
        working-directory: ./api-gateway
        run: |
          docker build \
            --build-arg whatsapp_verify_token=${{ secrets.WHATSAPP_VERIFY_TOKEN }} \
            --build-arg whatsapp_graph_api_token=${{ secrets.WHATSAPP_GRAPH_API_TOKEN }} \
            --build-arg whatsapp_app_secret=${{ secrets.WHATSAPP_APP_SECRET }} \
            -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/api-gateway/api-gateway:latest .

      - name: Configurar gcloud CLI
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Taggear a imagem com SHA
        run: docker tag us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/api-gateway/api-gateway:latest us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/api-gateway/api-gateway:${{ github.sha }}
      
      - name: Publicar a imagem no Artifact Registry
        run: |
          gcloud auth configure-docker us-docker.pkg.dev
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/api-gateway/api-gateway:latest
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/api-gateway/api-gateway:${{ github.sha }}